export const songs = [
  {
    path: `./audios/sudorytrabajo.mp3`,
    musicName: 'Sudor y Trabajo',
    artist: 'Duki',
    cover: `./images/sudorytrabajo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/endless.mp3`,
    musicName: 'The Endless Endeavor',
    artist: 'Starset',
    cover: `./images/endless.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/someonenew.mp3`,
    musicName: 'Someone New',
    artist: 'Hozier',
    cover: `./images/someonenew.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/shinunoga.mp3`,
    musicName: 'Shinunoga E-wa',
    artist: 'Fujii Kaze',
    cover: `./images/shinunoga.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/ricopobre.mp3`,
    musicName: 'RICO POBRE',
    artist: 'Julianno Sosa',
    cover: `./images/ricopobre.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/llegara.mp3`,
    musicName: 'Llegará',
    artist: 'Myke Towers',
    cover: `./images/llegara.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/rlndt.mp3`,
    musicName: 'RLNDT',
    artist: 'Bad Bunny',
    cover: `./images/rlndt.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/goteo.mp3`,
    musicName: 'Goteo',
    artist: 'Duki',
    cover: `./images/goteo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/necesario.mp3`,
    musicName: 'Necesario',
    artist: 'Quevedo',
    cover: `./images/pedroquevedo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/pedroquevedo.mp3`,
    musicName: 'Pedro Domínguez Quevedo',
    artist: 'Quevedo',
    cover: `./images/pedroquevedo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/otranoche.mp3`,
    musicName: 'Otra Noche',
    artist: 'Ángeles Azules ft. Nicki Nicole',
    cover: `./images/otranoche.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/noche.mp3`,
    musicName: 'Noche',
    artist: 'La Oreja De Van Gogh',
    cover: `./images/noche.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/tumelohacesfacil.mp3`,
    musicName: 'Tú Me Lo Haces Fácil',
    artist: 'Maria Becerra',
    cover: `./images/tumelohacesfacil.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/verano.mp3`,
    musicName: 'Verano',
    artist: 'La Oreja De Van Gogh',
    cover: `./images/verano.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/seraquenomeamas.mp3`,
    musicName: 'Será Que No Me Amas',
    artist: 'Luis Miguel',
    cover: `./images/seraquenomeamas.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/paris.mp3`,
    musicName: 'París',
    artist: 'La Oreja De Van Gogh',
    cover: `./images/paris.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/lookingover.mp3`,
    musicName: 'Looking Over Shoulders',
    artist: 'Yumi Zouma',
    cover: `./images/lookingover.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/lying.mp3`,
    musicName: 'Lying',
    artist: 'PRETTYMUCH ft. Tjay',
    cover: `./images/lying.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/visionsofgideon.mp3`,
    musicName: 'Visions of Gideon',
    artist: 'Susjan Steven',
    cover: `./images/visionsofgideon.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/hastaquemeolvides.mp3`,
    musicName: 'Hasta que me olvides',
    artist: 'Luis Miguel',
    cover: `./images/hastaquemeolvides.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/yelle.mp3`,
    musicName: 'Ce Jeu',
    artist: 'Yelle',
    cover: `./images/yelle.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/angeltusoledad.mp3`,
    musicName: 'Un Ángel para Tu Soledad',
    artist: 'Patricio Rey y sus Redonditos de Ricota',
    cover: `./images/angeltusoledad.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/nighteyes.mp3`,
    musicName: 'Night Eyes',
    artist: 'The Orion Experience',
    cover: `./images/nighteyes.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/perdidamente.mp3`,
    musicName: 'Perdidamente',
    artist: 'María Becerra',
    cover: `./images/perdidamente.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/rengadiabloymuerte.mp3`,
    musicName: 'La Balada del Diablo y La Muerte',
    artist: 'La Renga',
    cover: `./images/rengadiabloymuerte.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/antesdeperderte.mp3`,
    musicName: 'Antes de Perderte',
    artist: 'Duki',
    cover: `./images/antesdeperderte.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/ahoratepuedesmarchar.mp3`,
    musicName: 'Ahora te puedes marchar',
    artist: 'Luis Miguel',
    cover: `./images/ahoratepuedesmarchar.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/nude.mp3`,
    musicName: 'NUDE',
    artist: 'Kidd Keo',
    cover: `./images/nude.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/josesabia.mp3`,
    musicName: 'José Sabía',
    artist: 'La Vela Puerca',
    cover: `./images/josesabia.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/silopuedessoñar.mp3`,
    musicName: 'Si Lo Puedes Soñar',
    artist: 'Eladio Carrion',
    cover: `./images/silopuedessoñar.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/tengo30.mp3`,
    musicName: 'Tengo 30',
    artist: 'Khea ft Duki, Cazzu, Neo Pistea, Tali Goya',
    cover: `./images/tengo30.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/riosdesal.mp3`,
    musicName: 'Ríos de sal',
    artist: 'Tiago PZK',
    cover: `./images/tiago.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/magicshop.mp3`,
    musicName: 'Magic Shop',
    artist: 'BTS',
    cover: `./images/magicshop.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/saboramiel.mp3`,
    musicName: 'Sabor a Miel',
    artist: 'Tiago PZK',
    cover: `./images/tiago.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/blackswan.mp3`,
    musicName: 'Black Swan',
    artist: 'BTS',
    cover: `./images/blackswan.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/cieloenmente.mp3`,
    musicName: 'cielo en la mente',
    artist: 'Emilia',
    cover: `./images/cieloenmente.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/run.mp3`,
    musicName: 'Run',
    artist: 'BTS',
    cover: `./images/run.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/superstars.mp3`,
    musicName: 'Superstars',
    artist: 'Kidd Keo',
    cover: `./images/superstars.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/theastronaut.mp3`,
    musicName: 'The Astronaut',
    artist: 'JIN',
    cover: `./images/theastronaut.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/unpisomas.mp3`,
    musicName: 'Un piso más',
    artist: 'YSY A',
    cover: `./images/unpisomas.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/miculpa.mp3`,
    musicName: 'Mi Culpa',
    artist: 'Lit Killah ft C.R.O',
    cover: `./images/miculpa.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/meenseñastermx.mp3`,
    musicName: 'Me Enseñaste | REMIX',
    artist: 'Sael ft Duki',
    cover: `./images/meenseñastermx.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/personalmente.mp3`,
    musicName: 'Personalmente',
    artist: 'Las Pelotas',
    cover: `./images/personalmente.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/undiaperfecto.mp3`,
    musicName: 'Un día perfecto',
    artist: 'Estelares',
    cover: `./images/undiaperfecto.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/cuandoteenamores.mp3`,
    musicName: 'Cuando te enamores',
    artist: 'Antonio José, Luciano Pereyra',
    cover: `./images/cuandoteenamores.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/razon.mp3`,
    musicName: 'Razón',
    artist: 'Los Caligaris',
    cover: `./images/razon.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/nanana.mp3`,
    musicName: 'Na Na Na',
    artist: 'Luck Ra',
    cover: `./images/nanana.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/acaramelao.mp3`,
    musicName: 'ACARAMELAO',
    artist: 'María Becerra',
    cover: `./images/acaramelao.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/soldoutdates.mp3`,
    musicName: 'Sold Out Dates',
    artist: 'Duki',
    cover: `./images/soldoutdates.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/ojitoslindos.mp3`,
    musicName: 'Ojitos Lindos',
    artist: 'Bad Bunny, Bomba Estéreo',
    cover: `./images/ojitoslindos.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/dna.mp3`,
    musicName: 'DNA',
    artist: 'Kendrick Lamar',
    cover: `./images/dna.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/buenosairesenllamas.mp3`,
    musicName: 'BUENOS AIRES EN LLAMAS',
    artist: 'Trueno',
    cover: `./images/buenosairesenllamas.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/rapido.mp3`,
    musicName: 'Rápido',
    artist: 'Eladio Carrión ft Jon Z, Noriel',
    cover: `./images/rapido.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/youngflex.mp3`,
    musicName: 'Young Flex',
    artist: 'KHEA',
    cover: `./images/youngflex.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/chicoestrella.mp3`,
    musicName: 'Chico Estrella',
    artist: 'Duki',
    cover: `./images/chicoestrella.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/check.mp3`,
    musicName: 'Check (Spanish Version)',
    artist: 'Anuel AA',
    cover: `./images/check.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/cheque.mp3`,
    musicName: 'Cheque',
    artist: 'Eladio Carrión ft Jon Z, Noriel',
    cover: `./images/cheque.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/leyenda.mp3`,
    musicName: 'Leyenda',
    artist: 'Anuel AA',
    cover: `./images/leyenda.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/mama.mp3`,
    musicName: 'MAMA',
    artist: 'Anuel AA',
    cover: `./images/mama.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/miultimodeseo.mp3`,
    musicName: 'Mi último deseo',
    artist: 'Banda Los Recoditos',
    cover: `./images/miultimodeseo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/comosea.mp3`,
    musicName: 'Como Sea',
    artist: 'Eladio Carrión ft Arcangel',
    cover: `./images/comosea.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/dangerous.mp3`,
    musicName: 'Dangerous',
    artist: 'Nicki Nicole ft Trueno, Bizarrap',
    cover: `./images/dangerous.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/sherlock.mp3`,
    musicName: 'Sherlock',
    artist: 'oceanfromtheblue',
    cover: `./images/sherlock.jpg`,
    gender: 'TRAP',
  },
]
