export const songs = [
  {
    path: `./audios/sudorytrabajo.mp3`,
    musicName: 'Sudor y Trabajo',
    artist: 'Duki',
    cover: `./images/sudorytrabajo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/endless.mp3`,
    musicName: 'The Endless Endeavor',
    artist: 'Starset',
    cover: `./images/endless.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/someonenew.mp3`,
    musicName: 'Someone New',
    artist: 'Hozier',
    cover: `./images/someonenew.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/shinunoga.mp3`,
    musicName: 'Shinunoga E-wa',
    artist: 'Fujii Kaze',
    cover: `./images/shinunoga.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/ricopobre.mp3`,
    musicName: 'RICO POBRE',
    artist: 'Julianno Sosa',
    cover: `./images/ricopobre.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/llegara.mp3`,
    musicName: 'Llegará',
    artist: 'Myke Towers',
    cover: `./images/llegara.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/rlndt.mp3`,
    musicName: 'RLNDT',
    artist: 'Bad Bunny',
    cover: `./images/rlndt.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/goteo.mp3`,
    musicName: 'Goteo',
    artist: 'Duki',
    cover: `./images/goteo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/necesario.mp3`,
    musicName: 'Necesario',
    artist: 'Quevedo',
    cover: `./images/pedroquevedo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/pedroquevedo.mp3`,
    musicName: 'Pedro Domínguez Quevedo',
    artist: 'Quevedo',
    cover: `./images/pedroquevedo.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/otranoche.mp3`,
    musicName: 'Otra Noche',
    artist: 'Ángeles Azules ft. Nicki Nicole',
    cover: `./images/otranoche.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/noche.mp3`,
    musicName: 'Noche',
    artist: 'La Oreja De Van Gogh',
    cover: `./images/noche.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/tumelohacesfacil.mp3`,
    musicName: 'Tú Me Lo Haces Fácil',
    artist: 'Maria Becerra',
    cover: `./images/tumelohacesfacil.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/verano.mp3`,
    musicName: 'Verano',
    artist: 'La Oreja De Van Gogh',
    cover: `./images/verano.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/seraquenomeamas.mp3`,
    musicName: 'Será Que No Me Amas',
    artist: 'Luis Miguel',
    cover: `./images/seraquenomeamas.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/paris.mp3`,
    musicName: 'París',
    artist: 'La Oreja De Van Gogh',
    cover: `./images/paris.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/lookingover.mp3`,
    musicName: 'Looking Over Shoulders',
    artist: 'Luis Miguel',
    cover: `./images/lookingover.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/lying.mp3`,
    musicName: 'Lying',
    artist: 'PRETTYMUCH ft. Tjay',
    cover: `./images/lying.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/visionsofgideon.mp3`,
    musicName: 'Visions of Gideon',
    artist: 'Susjan Steven',
    cover: `./images/visionsofgideon.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/hastaquemeolvides.mp3`,
    musicName: 'Hasta que me olvides',
    artist: 'Luis Miguel',
    cover: `./images/hastaquemeolvides.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/yelle.mp3`,
    musicName: 'Yelle',
    artist: 'Ce Jeu',
    cover: `./images/yelle.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/angeltusoledad.mp3`,
    musicName: 'Un Ángel para Tu Soledad',
    artist: 'Patricio Rey y sus Redonditos de Ricota',
    cover: `./images/angeltusoledad.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/nighteyes.mp3`,
    musicName: 'Night Eyes',
    artist: 'The Orion Experience',
    cover: `./images/nighteyes.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/perdidamente.mp3`,
    musicName: 'Perdidamente',
    artist: 'María Becerra',
    cover: `./images/perdidamente.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/rengadiabloymuerte.mp3`,
    musicName: 'La Balada del Diablo y La Muerte',
    artist: 'La Renga',
    cover: `./images/rengadiabloymuerte.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/antesdeperderte.mp3`,
    musicName: 'Antes de Perderte',
    artist: 'Duki',
    cover: `./images/antesdeperderte.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/ahoratepuedesmarchar.mp3`,
    musicName: 'Ahora te puedes marchar',
    artist: 'Luis Miguel',
    cover: `./images/ahoratepuedesmarchar.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/nude.mp3`,
    musicName: 'NUDE',
    artist: 'Kidd Keo',
    cover: `./images/nude.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/josesabia.mp3`,
    musicName: 'José Sabía',
    artist: 'La Vela Puerca',
    cover: `./images/josesabia.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/silopuedessoñar.mp3`,
    musicName: 'Si Lo Puedes Soñar',
    artist: 'Eladio Carrion',
    cover: `./images/silopuedessoñar.jpg`,
    gender: 'TRAP',
  },
  {
    path: `./audios/tengo30.mp3`,
    musicName: 'Tengo 30',
    artist: 'Khea ft Duki, Cazzu, Neo Pistea, Tali Goya',
    cover: `./images/tengo30.jpg`,
    gender: 'TRAP',
  },
]
